server {
    listen 4000;
    location / {
        root /usr/share/nginx/html/web1;
        index index.html;
    }
}
server {
    listen 4001;
    location / {
        root /usr/share/nginx/html/web2;
        index index.html;
    }
}
